---
# ----------------------------------------------------------------------------------------
# -- Docs: https://github.com/cluster-apps-on-docker/spark-standalone-cluster-on-docker --
# ----------------------------------------------------------------------------------------
version: "3.6"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
services:
  nginx:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./labs:/usr/share/nginx/html
  jupyterlab:
    image: andreper/jupyterlab:3.0.0-spark-3.0.0
    container_name: jupyterlab
    deploy:
      resources:
        limits:
          cpus: 0.8
          memory: 60000m
    restart: unless-stopped
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - shared-workspace:/opt/workspace
